- name: Install nginx
  apt:
    name: nginx
    state: latest
    update_cache: yes
  tags:
    - install
    - ubuntu
    - nginx

- name: Get certificate via certbot for nginx
  shell: |
      certbot certonly --nginx --noninteractive --agree-tos \
      --email {{ cert_email }} -d {{ domain }}
  when: host_type == "public"
  tags:
    - ubuntu
    - build
    - certbot
    - nginx

- name: Copy nginx.https.conf
  template:
    src: nginx.https.conf
    dest: /etc/nginx/sites-available/default
  when: host_type == "public"
  tags:
    - start
    - ubuntu
    - nginx

- name: start nginx
  service:
    name: nginx
    state: started
  tags:
    - init
    - ubuntu
    - nginx
