- name: init node on a machine
  hosts:
    - stage_aws
  become: yes
  tasks:
    - name: Add global variables
      include_vars:
        file: "{{ playbook_dir }}/{{ item }}"
      with_items:
      - config.yml
      - config-root.yml
      tags:
        - configs


    - name: init nodes
      with_items:
        - "{{ validator_node }}"
        - "{{ sentery_node }}"
        - "{{ seed_node }}"
      vars:
        - node: "{{ item }}"
      include_role:
        name: node_init
      tags:
       - init

    - name: up service
      include_role:
        name: node_up
      tags:
        - up
    - name: up monitoring
      include_role:
        name: influx
      tags:
        - monitor
    - name: reset ssh connection
      meta: reset_connection
