# This is a basic workflow to help you get started with Actions

name: Test checkout

on:
  #push:
  #  branches: [ main ]
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout from mark
        uses: actions/checkout@v2
        with: 
          repository: markvandal/metabelarus.core.cr
          ref: build
      - 
        run: mkdir docker
      - 
        name: checkout Docerfile
        uses: actions/checkout@v2
        with:
          path: dockerfile
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docerfile/Dockerfile
          push: true
          tags: gordon77/mbcore:latest
